name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag alexcos78/web_server
    - name: Push the image to DockerHub
      run: docker login -u alexcos78 -p ${{ secrets.DOCKER_TOKEN }} && docker push alexcos78/web_server

